# Generated by Django 3.1.5 on 2021-01-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('author', models.CharField(max_length=10, verbose_name='author')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created-date')),
            ],
        ),
    ]
