# Generated by Django 3.1.5 on 2021-01-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(editable=False, max_length=10, verbose_name='author'),
        ),
    ]
